<div class="dashboard">

    <div>
        <?php echo $this->getMessagesBlock()->toHtml() ?>
    </div>

    <div class="page-title">
        <h1><?php echo $this->__('Credit Balance Request'); ?></h1>
    </div>

    <div>
    	<form action="<?php echo $this->getUrl('*/*/requestPost') ?>" id="creditRequestForm" method="post" class="scaffold-form">

		    <div class="fieldset">
		        <h2 class="legend"><?php echo Mage::helper('credit')->__('Credit Balance Request Form') ?></h2>

		        <ul class="form-list">
		            <li class="fields">

		                <div class="field">
		                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('credit')->__('Customer Email Id') ?></label>
		                    <div class="input-box">
		                        <input name="credit[email]" id="email" class="input-text required-entry validate-email" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" />
		                    </div>
		                </div>

		                <div class="field">
		                    <label for="amount" class="required"><em>*</em><?php echo Mage::helper('credit')->__('Enter Amount') ?></label>
		                    <div class="input-box">
		                        <input name="credit[amount]" id="number" class="input-number required-entry validate-email" type="number" />
		                    </div>
		                </div>

					    <div class="">
					        <button type="submit" class="button"><span><span><?php echo Mage::helper('credit')->__('Request') ?></span></span></button>
					    </div>

		            </li>
		        </ul>
		    </div>

		</form>
    </div>

    <br><hr><br>
  
    <div>

        <table class="data-table orders">
            <tr>
                <th>Transfer Id #</th>
                <th>From Customer</th>
                <th>Transfer Amount</th>
                <th>Status</th>
                <th>Detail</th>
                <th>requested_date</th>
            </tr>

            <?php $_collection = $this->getRequestedData();?>

            <?php if (!$_collection->getData()): ?>

            <tr style="text-align: center">
                <td colspan="6">No Request Found</td>
            </tr>

            <?php else: ?>
            <?php foreach ($_collection as $row): ?>

            <tr>
                <td><?php echo $row->getId(); ?></td>
                <td><?php echo $this->getCustomerEmail($row->getFromCustomerId()); ?></td>
                <td><?php echo $row->getTransactionAmount(); ?></td>
                <td><?php echo $this->getStatus($row->getTransferStatus()); ?></td>
                <td><?php echo $row->getDetail(); ?></td>
                <td><?php echo $row->getRequestedDate(); ?></td>
            </tr>

            <?php endforeach;?>
            <?php endif;?>
        </table>

    </div>
</div>